version: '3.8'
services:
  musicblocks:
    build: ./
    image: ghcr.io/sugarlabs/musicblocks:4-dev
    env_file:
      - ./env/development.env
    ports:
      - '5000:8080' # development server mapped to 5000
      - '5001:5000' # production http-server mapped to 5001
    volumes:
      - ./:/app/
    container_name: musicblocks-4-dev
    stdin_open: true
    tty: true
